// Code generated by Kitex v0.2.1. DO NOT EDIT.
package hello

import (
	"github.com/cloudwego/kitex/server"
	"github.com/guzhenyu/2022bytedance/kitex_example/hello2/kitex_gen/api"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler api.Hello, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
